name: Jenkins Backup

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch: # Manual trigger, you can also use schedule

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.JENKINS_SSH_KEY }}

    - name: Run Jenkins Backup Script via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.JENKINS_USER }}@${{ secrets.JENKINS_SERVER }} \
        "/usr/local/bin/jenkins_backup.sh"
